Final_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from landing_page import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", views.home, name="home"),
    path("", include("picture.urls")),
    path("gallery/", include("gallery.urls")),
    path("", include("main_page.urls")),
    path("maps/", include('maps.urls')), # temporary
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.all_pictures, name="all_pictures"),
    path("delete/", views.delete_multiple_pictures, name='delete-multiple-pictures'),
    path("download/", views.download_multiple_pictures, name='download-multiple-pictures'),
    path("tag/<slug:tag_slug>/",views.all_tagged_pictures, name="all_tagged_pictures"),
    path("new_gallery/", views.new_gallery, name="new_gallery"),
    path("<slug:gallery>/", views.gallery_detail, name="gallery_detail"),
    path(
        "picture_detail/<uuid:uuid>/delete_picture/",
        views.delete_picture,
        name="delete_picture",
    ),
    path(
        "picture_detail/<uuid:uuid>/",
        views.edit_picture,
        name="edit_picture",
    ),
    path(
        "picture_detail/<uuid:uuid>/<slug:galleryid>/",
        views.edit_gallery_picture,
        name="edit_gallery_picture",
    ),
    path("<slug:gallery>/delete_gallery/", views.delete_gallery, name="delete_gallery"),
    
]

maps/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Same url as picture_detail, this is just a placeholder
    path("<uuid:uuid>/", views.picture_detail_map, name="picture_detail_map"),
]

gallery/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class Gallery(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=80, null=False, blank=False)
    slug = models.SlugField(null=True, blank=True, unique=True)

    class Meta:
        verbose_name = "gallery"
        verbose_name_plural = "galleries"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Automatically create slug upon saving model.
        """
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

picture/models.py
from exiffield.fields import ExifField
from exiffield.getters import get_datetaken
from exiffield.exceptions import ExifError
import os.path
from io import BytesIO
import uuid

from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.db import models
from Final_Project.settings import THUMBNAIL_SIZE
from gallery.models import Gallery
from PIL import Image, ImageOps 
from taggit.managers import TaggableManager


def get_datetaken_safe(exif):
    """
    Overriding exiffield's get_datetaken to prevent it from throwing
    errors when a picture doesn't include EXIF data.
    """
    try:
        return_value = get_datetaken(exif)
    except ExifError or ValueError:
        return_value = None
    return return_value


class PicturesContainer(models.Model):
    """Container that holds multiple pictures upload"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_images")
    uploaded_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} pictures"


def get_image_upload_path(instance, filename):
    """Get the path to the image files"""
    return "images/user_{pictures_container_user}/{file}".format(
        pictures_container_user=instance.pictures_container.user.username, file=filename
    )


def get_thumb_upload_path(instance, filename):
    """Get path to the thumbnails"""
    return "thumbs/user_{pictures_container_user}".format(pictures_container_user=instance.pictures_container.user.username)


class Picture(models.Model):
    """
    Picture model with automatically generated thumbnail.
    """
    image = models.ImageField(upload_to=get_image_upload_path)

    # author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_images")
    title = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True) 
    gallery = models.ManyToManyField(Gallery, blank=True)

    thumbnail = models.ImageField(upload_to='thumbs')
    pictures_container = models.ForeignKey(PicturesContainer, on_delete=models.SET_NULL, null=True, blank=True)
    tags = TaggableManager(blank=True)  # help_text="A comma-separated list of tags."

    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    public_picture = models.BooleanField(default=False)
    public_link = models.BooleanField(default=False)

    #  METADATA
    created_on = models.DateTimeField(editable=False, blank=True, null=True, auto_now_add=True)
    exif = ExifField(
        source='image',
        denormalized_fields={
            'created_on': get_datetaken_safe,
        },
    )
    public_exif = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        """
        Make and save the thumbnail for the picture.
        """
        if not self.make_thumbnail():
            raise Exception(
                "Could not create thumbnail - check if the file type is valid."
            )

        super(Picture, self).save(*args, **kwargs)

    def make_thumbnail(self):
        """
        Create and save the thumbnail for the picture (simple resize with PIL).
        """
        thumb_image = Image.open(self.image)
        # We use our PIL Image object to create the thumbnail, which already has a thumbnail() method that contrains proportions.
        # Additionally, we use Image.ANTIALIAS to make the image look better.Without antialiasing the image pattern artifacts may result.
        # thumb_image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)
        thumb_image = ImageOps.fit(
            thumb_image,
            THUMBNAIL_SIZE,
            bleed=0.0,
            centering=(0.5, 0.5),
        )

        thumb_name, thumb_extension = os.path.splitext(self.image.name)
        thumb_extension = thumb_extension.lower()
        thumb_filename = thumb_name + "_thumb" + thumb_extension

        if thumb_extension in [".jpg", ".jpeg"]:
            FTYPE = "JPEG"
        elif thumb_extension == ".gif":
            FTYPE = "GIF"
        elif thumb_extension == ".png":
            FTYPE = "PNG"
        else:
            return False  # Unrecognized file type
        # Save thumbnail to in-memory file as StringIO
        temp_thumb = BytesIO()
        thumb_image.save(temp_thumb, FTYPE)
        temp_thumb.seek(0)
        # set save=False, otherwise it will run in an infinite loop
        self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()

        return True

    def __str__(self):
        return f"Image {self.pk}"

gallery/forms.py
from django import forms

from .models import Gallery


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = [
            "title",
        ]

picture/forms.py
from django import forms
from django.forms import ClearableFileInput

from .models import Picture, PicturesContainer
from gallery.models import Gallery
from django.contrib.auth.models import User


class PicturesContainerForm(forms.ModelForm):
    """ Form for uploading multiple pictures """
    class Meta:
        model = PicturesContainer
        fields = []
        
    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user')
        super(PicturesContainerForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        inst = super(PicturesContainerForm, self).save(commit=False) # Create, but don't save the new picture container instance.
        inst.user = self._user
        if commit:
            inst.save()  # Save the new instance.
            self.save_m2m()  #save the many-to-many data for the form.
        return inst


class PictureForm(forms.ModelForm):
    """Form for the picture model"""
    class Meta:
        model = Picture
        fields = ['image', 'title', 'description', 'tags', 'public_exif']
        widgets = {
            'image': ClearableFileInput(attrs={'multiple': True}),
        }
        # widget is important to upload multiple files

class DragAndDropPictureForm(forms.ModelForm):
    """Form for the picture model"""
    class Meta:
        model = Picture
        fields = ['image']

        widgets = {
            'image': ClearableFileInput(attrs={'multiple': True}),
        }
        # widget is important to upload multiple files

class EditPictureForm(forms.ModelForm):
    '''
    Form to assign/unassign gallery from an already-published photo.
    '''
    class Meta:
        model = Picture
        fields = ['id', 'title', 'description', 'gallery', 'tags', 'public_exif', 'public_picture', 'public_link']
    
    gallery = forms.ModelMultipleChoiceField(
        queryset=Gallery.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
    )

    def __init__(self, user, *args, **kwargs):
        '''
        Showing user-specific galleries + making choice of gallery
        optional.
        Had to override __init__ because gallery is now a ManyToMany field.
        '''
        super(EditPictureForm, self).__init__(*args, **kwargs)
        self.fields['gallery'].queryset = Gallery.objects.filter(user=user)
        self.fields['gallery'].required = False

class PublicPictureForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ["public_picture", "public_link"]

    public_picture = forms.BooleanField(
        label="Set picture as public",
        required=False,
    )

    public_link = forms.BooleanField(
        label="Show picture's direct link",
        required=False,
    )

gallery/templates/gallery/all_pictures.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pixel Hero - Viewing Picture</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon2.png' %}" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-shrink" style="background-color: #212529; position: fixed;" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">Pixel Hero</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'loggedin' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'picture-upload' %}">Upload</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout {{ request.user.username }}</a></li>
                    </ul>
                </div>
            </div>
        </nav>


        <section class="page-section bg-dark" id="carousel">
            <div class="container-xxl">

                <div class="row">
                    <div class="text-center">
                        <h2 style="color:whitesmoke" class="section-heading text-uppercase">Manage Page</h2>
                        <h3 style="color:whitesmoke" class="section-subheading"> This will be the Portfolio View</h3>
                    </div>

                </div>

                <div class="row">

                    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-indicators">
                            {% for picture in pictures %}
                                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.counter0 == 0 %} class="active" {% endif %} aria-current="true" aria-label="Slide {{ forloop.counter }}">

                                </button>
                            {% endfor %}
                        </div>
                        <div class="carousel-inner">

                            {% for picture in pictures %}
                            <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}" style="background-image: url({{ picture.image.url }})">

                            </div>
                            {% endfor %}

                        </div>

                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>

                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>

                </div>
            </div>

        </section>


        <!-- the edit section starts here -->

 <section class="page-section bg-light" id="portfolio">
            <div class="container">

                <div class="row">
                    <button><a href="{% url 'delete-multiple-pictures' %}">Delete multiple Pictures</a></button>
                    <button><a href="{% url 'download-multiple-pictures' %}">Download multiple Pictures</a></button>

                    <h2>Edit Picture </h2>
                    <br>
                    <img src="{{ picture.thumbnail.url }}" alt="User Photo">

                    <form method="POST">
                        {% csrf_token %}
                        <br>
                    <p><input type="text" name="title" {% if picture.title %} placeholder="{{ picture.title }}" {% else %} placeholder="add title" {% endif %} maxlength="100" id="id_title"></p>
                    <p><input type="text" name="description" {% if picture.description %} placeholder="{{ picture.description }}" {% else %} placeholder="add description" {% endif %} maxlength="255" id="id_description"></p>
                    <p><input type="text" name="tags" {% if picture.tags.all %} placeholder="{{ picture.tags.all }}" {% else %} placeholder="add tags (e.g. cats,nature)"  {% endif %} maxlength="255" id="id_tags"></p>

                    <div><label>This picture appears in:</label>
                        <div id="id_gallery">
                        <div><label for="id_gallery_0">
                            <input type="checkbox" name="gallery" value="2" id="id_gallery_0" checked="">
                    Color</label><br>
                    </div>
                    </div>
                </div>
                    <p>
                        <label for="id_public_exif">Public exif:</label>
                        <input type="checkbox" name="public_exif" id="id_public_exif" checked="">
                    </p>
                    <p>
                        <label for="id_public_picture">Set picture as public:</label> <input type="checkbox" name="public_picture" id="id_public_picture"></p>

                        <p>
                            <label for="id_public_link">Show picture's direct link:</label>
                            <input type="checkbox" name="public_link" id="id_public_link">


                        </p>
                    <br> <button>Update</button> <br><br> <a href="{% url 'all_pictures' %}">Back</a>
                    </form>

<div><a href="{% url 'mainpage' %}"> Back to main page </a></div>
</div>
</div>
</section>
        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; Pixel Hero 2022</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Think outside the Loop</a>
                        
                    </div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/galleries.js' %}" type="text/javascript"></script>
    </body>
</html>

gallery/templates/gallery/all_pictures2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pixel Hero - Viewing Picture</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon2.png' %}" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-shrink" style="background-color: #212529; position: fixed;" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">Pixel Hero</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'loggedin' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'picture-upload' %}">Upload</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout {{ request.user.username }}</a></li>
                    </ul>
                </div>
            </div>
        </nav>


        <section class="page-section bg-dark" id="carousel">
            <div class="container-xxl">

                <div class="row">
                    <div class="text-center">
                        <h2 style="color:whitesmoke" class="section-heading text-uppercase">Manage Page</h2>
                        <h3 style="color:whitesmoke" class="section-subheading">Here you can manage your pictures</h3>
                    </div>

                </div>

                <div class="row">

                    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-indicators">
                            {% for picture in pictures %}
                                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.counter0 == 0 %} class="active" {% endif %} aria-current="true" aria-label="Slide {{ forloop.counter }}">

                                </button>
                            {% endfor %}
                        </div>
                        <div class="carousel-inner">

                            {% for picture in pictures %}
                            <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}" style="background-image: url({{ picture.image.url }})">

                            </div>
                            {% endfor %}

                        </div>

                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>

                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>

                </div>
            </div>

        </section>

        <section class="page-section bg-light" id="portfolio">
            <div class="container">

                <div class="row">
                    <div class="text-center">


                        <h2 class="section-heading text-uppercase"></h2>
                        <h3 class="section-subheading text-muted">Tags</h3>

                        {% for tag in tags %}
                            <button class="btn btn-primary" type="button"><a class="btn btn-primary" href="{% url 'all_tagged_pictures' tag.slug %}" >#{{ tag.name }}</a></button>
                        {% endfor %}
                    </div>

                </div>

                <div class="row">

                    <div class="text-center">
                        <h2 class="section-heading text-uppercase"></h2>
                        <h3 class="section-subheading text-muted">Galleries</h3>
                    </div>

                    {% for gallery in galleries %}
                        <div class="col-lg-4 col-sm-6 mb-4">
                            <div class="gallery-item shadow-lg">
                                <a class="gallery-link" href="{% url 'gallery_detail' gallery.slug %}">
                                    <div class="gallery-hover">
                                        <div class="gallery-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                    </div>
                                    <img width="1920" height="1280" src="" class="img-fluid" alt="{{ gallery.title }}">
                                </a>
                            </div>
                        </div>    
                    {% empty %}

                        <div class="col-lg-12 col-sm-12 mb-12">
                            <div class="gallery-item">
                                You don't have any galleries yet.
                            </div>
                            <a href="{% url 'new_gallery' %}">Create one now!</a>
                        </div>

                    {% endfor %}

                    <div class="gallery-item shadow-lg">
                        <li>
                            <a href="{% url 'new_gallery' %}">New Gallery...</a>
                        </li>
                    </div>
                    
                </div>

            </div>

        </section>


        

        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; Pixel Hero 2022</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Think outside the Loop</a>
                        
                    </div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/galleries.js' %}" type="text/javascript"></script>
    </body>
</html>

gallery/templates/gallery/delete_multiple.html
   <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete multiple pictures</title>
</head>
<body>
    <h2>Select pictures you want to delete</h2>
    
    <div><button type="button" id="SelectAll">Select All</button></div>
    <div><button type="button" id="UnselectAll">Clear selection</button></div>

{% csrf_token %}
{% for picture in pictures %}
<div id='picture-{{ picture.id }}'>
    <img src="{{ picture.thumbnail.url }}">
    <input type="checkbox" name="picture_id[]" value="{{ picture.id }}" id="delete_picture">
</div>
    
{% endfor %}  

<div><button type="submit" class="btn_delete" id="delete_btn">Delete</button></div>

<script>

window.addEventListener('load', () => {

    document.getElementById('SelectAll').onclick = function() {
            event.preventDefault()
            let checkboxes = Array.from(document.querySelectorAll('input[type=checkbox]'))
            checkboxes.forEach((el) => {el.checked = true})
        }

        document.getElementById('UnselectAll').onclick = function() {
            event.preventDefault()
            let checkboxes = Array.from(document.querySelectorAll('input[type=checkbox]'))
            checkboxes.forEach((el) => {el.checked = false})
        }

        document.querySelector('#delete_btn').addEventListener('click', event => {
            event.preventDefault()
            if(confirm('Do you want to delete those images?')){
                const csrf=document.querySelector('input[name=csrfmiddlewaretoken').value
                const ids = Array.from(document.querySelectorAll('input[type=checkbox]:checked'))
                if(ids.length===0) {
                    alert('Please select items to delete')
                } else {
                    const data = new FormData()
                    ids.forEach((el) => {
                        data.append('id[]', el.value)
                    })
                    data.append('csrfmiddlewaretoken', csrf)
                    fetch('.', {
                        method: 'POST',
                        headers: {
                            'Accept': 'application/json',
                            'X-CSRFToken': csrf
                        },
                        credentials: 'same-origin',
                        body: data
                        
                    }).then(response => {if (!response.ok){
                        alert('Server Error')
                        return
                    }
                    
                    ids.forEach(id =>  removeFadeOut(document.getElementById(`picture-${id.value}`), 200))


                }
                    )

                }

            }
        })
    })

    function removeFadeOut( el, speed ) {
    var seconds = speed/1000;
    el.style.transition = "opacity "+seconds+"s ease";
    el.style.opacity = 0;
    setTimeout(function() {
        el.parentNode.removeChild(el);
    }, speed);
}

    function checkAll() {
        let checkboxes = document.getElementsByTagName('input')    
        for (let i = 0; i < checkboxes.length; i++) {
            if (checkboxes[i].type == 'checkbox') {
            checkboxes[i].setAttribute('checked', true)
            }
        }
    }

</script>
</body>
</html>